In [6]:
import numpy as np
#  it will convert list into array
arr1= np.array([1,2,3,4])
print('this is the array:',arr1)
# arrange function takes step that is given
arr2=np.arange(5, 10, 2)  #it is taking step of 2 from num 5 to 10
print('this is arrange method: ',arr2)
# linespace breaks array into no. of parts given by user
arr3=np.linspace(1,10,7) #it is dividing into seven equal parts
print('this is the linespace method: ',arr3)


this is the array: [1 2 3 4]
this is arrange method:  [5 7 9]
this is the linespace method:  [ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [7]:
# creating 2d arrays
create_2darray=np.array([[1,2,3],[4,5,6]])
print('this is the 2d array: ',create_2darray)

this is the 2d array:  [[1 2 3]
 [4 5 6]]


In [8]:
# shape datatype size dimesional
myarray=np.array([[1,2,3],[4,5,6]])
print(myarray.shape)  #tells about rows and columns
print(myarray.dtype)   #tells about datatype
print(myarray.size)    # tell about total elemnts in 2d_array
print(myarray.ndim)     # tells about dimenssion 

(2, 3)
int64
6
2


In [10]:
import numpy as np
arr= np.array([11,22,33,44])
print(arr[1])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0:2,1:2]) #getting only specific elements
# print(arr2d[0:,2:2])

22
[[2]
 [5]]


In [22]:
# reshape transpose sort maxvalue
arr = np.array([3, 1, 4, 2])
print(arr.reshape(2, 2))
print(arr.transpose())
# print(arr.sort())
print(np.sort(arr))
print(arr.argmax())


[[3 1]
 [4 2]]
[3 1 4 2]
[1 2 3 4]
2


In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Add:", arr1 + arr2)
print("Sub:", arr1 - arr2)
print("Mul:", arr1 * arr2)
print("Div:", arr1 / arr2)
print("Flordiv:", arr1 // arr2)
print("Modulo:", arr1 % arr2)

Add: [5 7 9]
Sub: [-3 -3 -3]
Mul: [ 4 10 18]
Div: [0.25 0.4  0.5 ]
Flordiv: [0 0 0]
Modulo: [1 2 3]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))

[ 1  4  9 16 25]


In [21]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr))
print(np.sum(arr))

3.0
3.0
2.0
1.4142135623730951
5
15


In [23]:
# Create a 2D array
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

# Transpose the array
arr_transposed = np.transpose(arr)

print(arr)
print(arr_transposed)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
