# EDA for Python Libraries
## Numpy

In [1]:
import numpy as np


In [18]:
array_1=([1,2,3,4,5],[6,7,8,9,10])
np.shape(array_1)
np.transpose(array_1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [51]:
arr=np.array([[1,2,3,4,5],[10,9,8,7,6]])
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.T)
print(arr.sum())
print(arr[0,3])   #only printing a specific element
print(arr.argmax())
print(arr.ndim)
print(arr.argmin())
print(np.sort(arr))

[[ 1  2  3  4  5]
 [10  9  8  7  6]]
int64
(2, 5)
[[ 1 10]
 [ 2  9]
 [ 3  8]
 [ 4  7]
 [ 5  6]]
55
4
5
2
0
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
import numpy as np
arr1=np.array([11,22,33])
arr2=np.array([4,3,2])
print('add: ',arr1+arr2)
print('sub: ',arr1-arr2)
print('mul: ',arr1*arr2)
print('div: ',arr1/arr2)
print('flordiv: ',arr1//arr2)
print('modo: ',arr1%arr2)
print('equals: ',arr1==arr2)
print('less: ',arr1<arr2)
print('greater: ',arr1>arr2)
print('not equal: ',arr1!=arr2)
print('greater or equal to: ',arr1>=arr2)



add:  [15 25 35]
sub:  [ 7 19 31]
mul:  [44 66 66]
div:  [ 2.75        7.33333333 16.5       ]
flordiv:  [ 2  7 16]
modo:  [3 1 1]
equals:  [False False False]
equals:  [3 1 1]
less:  [False False False]
greater:  [ True  True  True]
not equal:  [ True  True  True]
greater or equal to:  [ True  True  True]


In [50]:
import numpy as np
arr= np.array([11,22,33,44])
print(arr[1])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0:2,1:2]) #getting only specific elements
# print(arr2d[0:,2:2])

22
[[2]
 [5]]


In [52]:
arr1=np.array([11,22,33])
print(arr1.sum())


66
